export const LOGINDATA_UPDATE = 'LOGINDATA_UPDATE';
export const USER_DETAIL = "USER_DETAIL";
export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const EMPLOYEE_IMAGE = "EMPLOYEE_IMAGE";
export const EMPLOYEE_DATA = "EMPLOYEE_DATA";
export const PUBLIC_HOLIDAY = "PUBLIC_HOLIDAY";